version: "3.7"
services:
  varnish:
    image: varnish:latest
    restart: always
    ports:
      - "80:80"
      - "6085:6085"
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    volumes:
      - "./conf/varnish/:/etc/varnish/"
    depends_on:
      - "nginx"
    links:
      - "nginx"      
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./www/:/var/www/html/"
      - "./conf/vhost/:/etc/nginx/conf.d/"
      - "./logs/nginx/:/var/log/nginx/"
      - "./conf/ssl/:/etc/nginx/ssl/"
    links:
      - php81
      - php74
  php81:
    build:
      context: ./bin/php81/
    restart: always
    volumes:
      - "./www/:/var/www/html/"
  php74:
    build:
      context: ./bin/php74/
    restart: always
    volumes:
      - "./www/:/var/www/html/"
  php73:
    build:
      context: ./bin/php73/
    restart: always
    volumes:
    - "./www/:/var/www/html/"
  php72:
    build:
      context: ./bin/php72/
    restart: always
    volumes:
    - "./www/:/var/www/html/"
  php56:
    build:
      context: ./bin/php56/
    restart: always
    volumes:
    - "./www/:/var/www/html/"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch-node1
    restart: always
    environment:
      - bootstrap.memory_lock=true 
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - "9400:9200"
      - "9600:9600" # required for Performance Analyzer
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=luxinten
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: luxinten
    ports:
      - "5000:80"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  mysql-data:
